lifter:
  subsystem: "lifter"
  description: "All motors used in the robot lifter mechanism live here for the lifter component"
  motors:
    groups: "motors" 
    winchMotor:
      channel: 40
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"
        sensorPhase: True
        currentLimits:
          freeLimit: 30
          stallLimit: 30
          stallLimitRPM: 50
          secondaryLimit: 35
      pid: Null

description: "Base file stuff"
