lifter:
  subsystem: "lifter"
  description: "All motors used in the robot lifter mechanism live here for the lifter component"
  motors:
    groups: "motors" 
    winchMotor:
      channel: 40
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"
      pid:
        controlType: "Velocity"
        feedbackDevice: 2
        kPreScale: 6
        kP: .1
        kD: 0
        kI: .0000001
        kF: 0
        sensorPhase: True
        currentLimits:
          freeLimit: 30
          stallLimit: 30
          stallLimitRPM: 50
          secondaryLimit: 35

description: "Base file stuff"
