winch:
  subsystem: "winch"
  description: "All motors used in the robot winch mechanism live here for the winch component"
  motors:
    groups: "motors" 
    winchMotor:
      channel: 40
      type: "SparkMax"
      inverted: True
      motorType: "kBrushless"
      sensorPhase: True
      currentLimits:
        freeLimit: 30
        stallLimit: 30
        stallLimitRPM: 50
        secondaryLimit: 35
      pid: Null

description: "Base file stuff"
